export const verbList: VerbData[] = [
  // サ変動詞
  { kanji: '勉強する', kana: 'べんきょうする', type: 'suru', meaning: '学习' },
  { kanji: '研究する', kana: 'けんきゅうする', type: 'suru', meaning: '研究，调查' },
  { kanji: '進化する', kana: 'しんかする', type: 'suru', meaning: '进化' },
  { kanji: '挑戦する', kana: 'ちょうせんする', type: 'suru', meaning: '挑战，尝试' },
  { kanji: '決定する', kana: 'けっていする', type: 'suru', meaning: '决定' },
  { kanji: '操作する', kana: 'そうさする', type: 'suru', meaning: '操作，使用' },
  { kanji: '発達する', kana: 'はったつする', type: 'suru', meaning: '发展，成长' },
  { kanji: '経験する', kana: 'けいけんする', type: 'suru', meaning: '经验，体验' },
  { kanji: '改善する', kana: 'かいぜんする', type: 'suru', meaning: '改善' },
  { kanji: '体験する', kana: 'たいけんする', type: 'suru', meaning: '体验，经历' },
  //　カ変動詞
  { kanji: '来る', kana: 'くる', type: 'kuru', meaning: '来' },
  // 五段动词 & 一段动词
  { kanji: '出す', kana: 'だす', type: 'v5', meaning: '发送' },
  { kanji: '待つ', kana: 'まつ', type: 'v5', meaning: '等待' },
  { kanji: '読む', kana: 'よむ', type: 'v5', meaning: '读' },
  { kanji: '感じる', kana: 'かんじる', type: 'v1', meaning: '感觉' },
  { kanji: '話す', kana: 'はなす', type: 'v5', meaning: '说' },
  { kanji: '見る', kana: 'みる', type: 'v1', meaning: '看' },
  { kanji: '教える', kana: 'おしえる', type: 'v1', meaning: '教授' },
  { kanji: '買う', kana: 'かう', type: 'v5', meaning: '购买' },
  { kanji: '描く', kana: 'かく', type: 'v5', meaning: '描绘' },
  { kanji: '祈る', kana: 'いのる', type: 'v5', meaning: '祈祷' },
  { kanji: '起きる', kana: 'おきる', type: 'v1', meaning: '起床' },
  { kanji: '切る', kana: 'きる', type: 'v5', meaning: '割开' },
  { kanji: '寝る', kana: 'ねる', type: 'v1', meaning: '睡觉' },
  { kanji: '求める', kana: 'もとめる', type: 'v1', meaning: '求' },
  { kanji: '上がる', kana: 'あがる', type: 'v5', meaning: '上升' },
  { kanji: '食べる', kana: 'たべる', type: 'v1', meaning: '吃' },
  { kanji: '使う', kana: 'つかう', type: 'v5', meaning: '使用' },
  { kanji: '書く', kana: 'かく', type: 'v5', meaning: '写' },
  { kanji: '思う', kana: 'おもう', type: 'v5', meaning: '思考' },
  { kanji: '死ぬ', kana: 'しぬ', type: 'v5', meaning: '死' },
  { kanji: '送る', kana: 'おくる', type: 'v5', meaning: '送' },
  { kanji: '嘆く', kana: 'なげく', type: 'v5', meaning: '叹息' },
  { kanji: '聞く', kana: 'きく', type: 'v5', meaning: '听' },
  { kanji: '洗う', kana: 'あらう', type: 'v5', meaning: '洗' },
  { kanji: '行く', kana: 'いく', type: 'v5', meaning: '前往' },
  { kanji: '休む', kana: 'やすむ', type: 'v5', meaning: '休息' },
  { kanji: '飲む', kana: 'のむ', type: 'v5', meaning: '喝' },
  { kanji: '泳ぐ', kana: 'およぐ', type: 'v5', meaning: '游泳' },
  { kanji: '止める', kana: 'とめる', type: 'v1', meaning: '停止' },
  { kanji: '走る', kana: 'ある', type: 'v5', meaning: '步行' },
  { kanji: '作る', kana: 'つくる', type: 'v5', meaning: '做' },
  { kanji: 'やる', kana: 'やる', type: 'v5', meaning: '做（口语）' },
];
